"""Pydantic schemas representing objectified database tables.

These map to objectified.account, objectified.tenant, objectified.tenant_account,
objectified.project, objectified.version, objectified.property, objectified.class,
objectified.class_property. Used for OpenAPI documentation and future CRUD services.
"""

from app.schemas.account import (
    AccountCreate,
    AccountLifecycleEventSchema,
    AccountSchema,
    AccountUpdate,
    ProfileUpdate,
    UserDeactivateBody,
    UserListSort,
    UserListStatus,
)
from app.schemas.auth import (
    ApiKeyCreate,
    ApiKeyCreateResponse,
    ApiKeySchema,
    LoginRequest,
    LoginResponse,
)
from app.schemas.catalog import (
    CatalogClassSummary,
    CatalogProjectEntry,
    CatalogProjectSummary,
    CatalogTenantEntry,
    CatalogTenantSummary,
    CatalogVersionSummary,
)
from app.schemas.class_model import ClassCreate, ClassSchema, ClassUpdate
from app.schemas.class_property import (
    ClassPropertyCreate,
    ClassPropertySchema,
    ClassPropertyUpdate,
)
from app.schemas.project import ProjectCreate, ProjectHistorySchema, ProjectSchema, ProjectUpdate
from app.schemas.property import PropertyCreate, PropertySchema, PropertyUpdate
from app.schemas.tenant import (
    TenantActivitySummarySchema,
    TenantAppearanceUpdate,
    TenantCreate,
    TenantQuotaStatusSchema,
    TenantSchema,
    TenantUpdate,
)
from app.schemas.tenant_admin_audit import (
    TenantAdminAuditEventSchema,
    TenantPrimaryAdminTransfer,
)
from app.schemas.tenant_account import (
    TenantAccessLevel,
    TenantAccountCreate,
    TenantAccountSchema,
    TenantAccountUpdate,
    TenantAdministratorCreate,
    TenantBulkInviteResultEntry,
    TenantMemberInvitationCreate,
    TenantMemberInvitationSchema,
    TenantMemberInvitationStatus,
    TenantMemberInviteOutcome,
    TenantMemberListEntrySchema,
    TenantMemberRoleSchema,
    TenantMembersBulkInvite,
    TenantMembersBulkInviteResponse,
    TenantMembersBulkRemove,
)
from app.schemas.user_memberships import (
    UserMembershipRoleSchema,
    UserTenantMembershipAdminSchema,
)
from app.schemas.sso import (
    SsoProviderCreate,
    SsoProviderSchema,
    SsoProviderType,
    SsoProviderUpdate,
)
from app.schemas.version import (
    VersionCreate,
    VersionCreateFromRevision,
    VersionHistorySchema,
    VersionMetadataUpdate,
    VersionSchema,
    VersionUpdate,
    VersionVisibility,
)
from app.schemas.rbac import (
    AccountRoleAssignmentCreate,
    EffectivePermissionsResponse,
    PermissionSchema,
    RoleCreate,
    RolePermissionsUpdate,
    RoleSchema,
    RoleUpdate,
)
from app.schemas.schema_promotions import (
    SchemaEnvironment,
    SchemaLiveVersionDetail,
    SchemaLiveVersionSchema,
    SchemaPromotionRequest,
    SchemaPromotionSchema,
    SchemaPromoteResponse,
)

__all__ = [
    "AccountCreate",
    "AccountLifecycleEventSchema",
    "AccountSchema",
    "AccountUpdate",
    "ApiKeyCreate",
    "ApiKeyCreateResponse",
    "ApiKeySchema",
    "LoginRequest",
    "LoginResponse",
    "ClassCreate",
    "ClassSchema",
    "ClassUpdate",
    "ClassPropertyCreate",
    "ClassPropertySchema",
    "ClassPropertyUpdate",
    "ProfileUpdate",
    "UserDeactivateBody",
    "UserListSort",
    "UserListStatus",
    "ProjectCreate",
    "ProjectHistorySchema",
    "ProjectSchema",
    "ProjectUpdate",
    "PropertyCreate",
    "PropertySchema",
    "PropertyUpdate",
    "TenantAccessLevel",
    "TenantAccountCreate",
    "TenantAccountSchema",
    "TenantAccountUpdate",
    "TenantAdministratorCreate",
    "TenantBulkInviteResultEntry",
    "TenantMemberInvitationCreate",
    "TenantMemberInvitationSchema",
    "TenantMemberInvitationStatus",
    "TenantMemberInviteOutcome",
    "TenantMemberListEntrySchema",
    "TenantMemberRoleSchema",
    "TenantMembersBulkInvite",
    "TenantMembersBulkInviteResponse",
    "TenantMembersBulkRemove",
    "UserMembershipRoleSchema",
    "UserTenantMembershipAdminSchema",
    "TenantActivitySummarySchema",
    "TenantQuotaStatusSchema",
    "TenantAdminAuditEventSchema",
    "TenantAppearanceUpdate",
    "TenantCreate",
    "TenantPrimaryAdminTransfer",
    "TenantSchema",
    "TenantUpdate",
    "SsoProviderCreate",
    "SsoProviderSchema",
    "SsoProviderType",
    "SsoProviderUpdate",
    "VersionCreate",
    "VersionCreateFromRevision",
    "VersionHistorySchema",
    "VersionMetadataUpdate",
    "VersionSchema",
    "VersionUpdate",
    "VersionVisibility",
    "PermissionSchema",
    "RoleSchema",
    "RoleCreate",
    "RoleUpdate",
    "RolePermissionsUpdate",
    "AccountRoleAssignmentCreate",
    "SchemaEnvironment",
    "SchemaPromotionRequest",
    "SchemaLiveVersionSchema",
    "SchemaPromotionSchema",
    "SchemaPromoteResponse",
    "SchemaLiveVersionDetail",
    "EffectivePermissionsResponse",
    "CatalogClassSummary",
    "CatalogProjectEntry",
    "CatalogProjectSummary",
    "CatalogTenantEntry",
    "CatalogTenantSummary",
    "CatalogVersionSummary",
]
